version: '3.7'
services:
  backstage:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:80"
    environment:
      KYCLOAK_REALM: "admin"
      KEYCLOAK_AUTH_URL: "http://localhost:8080/auth/"
      KEYCLOAK_CLIENT_ID: "my-react-client"